import { useEffect, useMemo, useState } from 'react';
import { CalendarRange, CheckCircle2, ClipboardList, Download, LogOut, Search, Trash2, Users, XCircle } from 'lucide-react';
import { appointmentService } from '../services/appointmentService';
import type { Appointment, AppointmentStatus } from '../types/appointment';
const statuses:AppointmentStatus[]=['Agendado','Confirmado','Concluído','Cancelado'];

function AdminLogin({onLogin}:{onLogin:()=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');function submit(e:React.FormEvent){e.preventDefault();if(email==='admin@agendapro.com'&&password==='123456'){sessionStorage.setItem('agenda-admin','true');onLogin();}else setError('E-mail ou senha incorretos.');}return <section className="login-section"><div className="login-card"><span className="brand-icon large"><ClipboardList size={30}/></span><span className="eyebrow">Ãrea restrita</span><h1>Acesse o painel</h1><p>Use as credenciais demonstrativas para administrar os agendamentos.</p><form onSubmit={submit}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<div className="alert error">{error}</div>}<button className="primary-button">Entrar no painel</button></form><div className="demo-credentials"><strong>Credenciais de demonstração</strong><span>admin@agendapro.com</span><span>Senha: 123456</span></div></div></section>}

export function AdminPage(){const [logged,setLogged]=useState(()=>sessionStorage.getItem('agenda-admin')==='true');const [items,setItems]=useState<Appointment[]>(()=>appointmentService.list());const [dateFilter,setDateFilter]=useState('');const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState<'Todos'|AppointmentStatus>('Todos');
useEffect(()=>{const refresh=()=>setItems(appointmentService.list());window.addEventListener('appointments-updated',refresh);return()=>window.removeEventListener('appointments-updated',refresh)},[]);
const filtered=useMemo(()=>items.filter(i=>{const term=search.toLowerCase();return(!dateFilter||i.date===dateFilter)&&(!term||i.name.toLowerCase().includes(term)||i.phone.includes(term)||i.service.toLowerCase().includes(term))&&(statusFilter==='Todos'||i.status===statusFilter)}),[items,dateFilter,search,statusFilter]);
if(!logged)return <AdminLogin onLogin={()=>setLogged(true)}/>;
const today=new Date().toISOString().slice(0,10); const stats={total:items.length,today:items.filter(i=>i.date===today&&i.status!=='Cancelado').length,confirmed:items.filter(i=>i.status==='Confirmado').length,completed:items.filter(i=>i.status==='Concluído').length,cancelled:items.filter(i=>i.status==='Cancelado').length};
function remove(id:string){if(confirm('Deseja realmente excluir este agendamento? Esta ação não pode ser desfeita.'))appointmentService.remove(id)}
function exportCsv(){const rows=[['Cliente','Telefone','Serviço','Data','Horário','Status'],...filtered.map(i=>[i.name,i.phone,i.service,i.date,i.time,i.status])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>`"${v}"`).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='agendamentos.csv';a.click();URL.revokeObjectURL(a.href)}
return <section className="container admin-section"><div className="admin-title"><div><span className="eyebrow">Painel administrativo</span><h1>Visão geral da agenda</h1><p>Acompanhe atendimentos, clientes e desempenho em um só lugar.</p></div><div className="admin-actions"><button className="secondary-button" onClick={exportCsv}><Download size={17}/>Exportar CSV</button><button className="icon-text-button" onClick={()=>{sessionStorage.removeItem('agenda-admin');setLogged(false)}}><LogOut size={17}/>Sair</button></div></div>
<div className="stats-grid"><div className="stat-card"><span className="stat-icon"><Users/></span><div><strong>{stats.total}</strong><span>Total</span></div></div><div className="stat-card"><span className="stat-icon"><CalendarRange/></span><div><strong>{stats.today}</strong><span>Hoje</span></div></div><div className="stat-card"><span className="stat-icon"><CheckCircle2/></span><div><strong>{stats.completed}</strong><span>Concluídos</span></div></div><div className="stat-card"><span className="stat-icon"><XCircle/></span><div><strong>{stats.cancelled}</strong><span>Cancelados</span></div></div></div>
<div className="panel admin-panel"><div className="status-tabs">{(['Todos',...statuses] as const).map(s=><button key={s} className={statusFilter===s?'active':''} onClick={()=>setStatusFilter(s)}>{s}<span>{s==='Todos'?items.length:items.filter(i=>i.status===s).length}</span></button>)}</div><div className="filters"><label className="search-field"><Search size={18}/><input placeholder="Buscar cliente, telefone ou serviço" value={search} onChange={e=>setSearch(e.target.value)}/></label><input type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/>{(search||dateFilter||statusFilter!=='Todos')&&<button className="ghost-button" onClick={()=>{setSearch('');setDateFilter('');setStatusFilter('Todos')}}>Limpar filtros</button>}</div><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>ServiÃ§o</th><th>Data e horÃ¡rio</th><th>Status</th><th>Excluir</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.name}</strong><span>{item.phone}</span></td><td><strong>{item.service}</strong>{item.notes&&<span title={item.notes}>{item.notes}</span>}</td><td><strong>{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')}</strong><span>{item.time}</span></td><td><select className={`status-select status-${item.status.toLowerCase()}`} value={item.status} onChange={e=>appointmentService.updateStatus(item.id,e.target.value as AppointmentStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><button className="icon-button" title="Excluir agendamento" onClick={()=>remove(item.id)}><Trash2 size={18}/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={5} className="empty"><ClipboardList size={32}/><strong>Nenhum agendamento encontrado</strong><span>Tente alterar os filtros utilizados.</span></td></tr>}</tbody></table></div></div></section>}





