import { useMemo, useState } from 'react';
import { CalendarCheck, CheckCircle2, Clock3, ShieldCheck, Sparkles, Wrench, Headphones, Settings2, X } from 'lucide-react';
import { appointmentService } from '../services/appointmentService';
import type { Appointment, AppointmentFormData } from '../types/appointment';

const services = [
  { name:'Consultoria', description:'Análise personalizada para encontrar a melhor solução.', duration:'50 min', icon:Sparkles },
  { name:'Manutenção', description:'Diagnóstico e correção preventiva ou corretiva.', duration:'60 min', icon:Wrench },
  { name:'Instalação', description:'Configuração completa com orientação de uso.', duration:'90 min', icon:Settings2 },
  { name:'Suporte técnico', description:'Atendimento rápido para dúvidas e problemas.', duration:'40 min', icon:Headphones },
];
const times = ['08:00','09:00','10:00','11:00','13:00','14:00','15:00','16:00','17:00'];
const initial: AppointmentFormData = { name:'', phone:'', service:'', date:'', time:'', notes:'' };

function formatPhone(value:string){ const n=value.replace(/\D/g,'').slice(0,11); if(n.length<=2)return n; if(n.length<=6)return `(${n.slice(0,2)}) ${n.slice(2)}`; if(n.length<=10)return `(${n.slice(0,2)}) ${n.slice(2,6)}-${n.slice(6)}`; return `(${n.slice(0,2)}) ${n.slice(2,7)}-${n.slice(7)}`; }

export function ClientPage(){
  const [form,setForm]=useState(initial); const [error,setError]=useState(''); const [confirmation,setConfirmation]=useState<Appointment|null>(null);
  const occupied=useMemo(()=>form.date?appointmentService.occupiedTimes(form.date):[],[form.date,confirmation]);
  const minDate=new Date().toISOString().slice(0,10);
  function update(field:keyof AppointmentFormData,value:string){ setForm(p=>({...p,[field]:value,...(field==='date'?{time:''}:{})})); setError(''); }
  function submit(e:React.FormEvent){ e.preventDefault(); if(!form.name.trim()||!form.phone.trim()||!form.service||!form.date||!form.time){setError('Preencha os campos obrigatórios para continuar.');return;} if(form.name.trim().length<3){setError('Informe seu nome completo.');return;} if(form.phone.replace(/\D/g,'').length<10){setError('Informe um telefone válido com DDD.');return;} try{const item=appointmentService.create({...form,name:form.name.trim()});setConfirmation(item);setForm(initial);window.scrollTo({top:0,behavior:'smooth'});}catch(err){setError(err instanceof Error?err.message:'Não foi possível agendar.');}}
  return <>
    <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Agendamento simples e inteligente</span><h1>Seu atendimento, organizado do início ao fim.</h1><p>Escolha o serviço, encontre um horário livre e confirme em poucos passos. Sem ligações, sem espera e sem conflito de agenda.</p><div className="features"><span><Clock3 size={18}/>Disponibilidade atualizada</span><span><ShieldCheck size={18}/>Confirmação imediata</span></div></div><div className="hero-visual"><div className="floating-card card-a"><span>Próximo horário</span><strong>Hoje, 14:00</strong></div><div className="calendar-art"><CalendarCheck size={64}/><strong>Agenda sob controle</strong><span>Uma experiência simples para clientes e administradores.</span></div><div className="floating-card card-b"><CheckCircle2 size={18}/><span>Reserva confirmada</span></div></div></div></section>

    <section className="container services-section"><div className="section-heading"><div><span className="eyebrow">Nossos serviços</span><h2>Escolha o atendimento ideal</h2></div><p>Serviços demonstrativos para apresentar o funcionamento completo da aplicação.</p></div><div className="service-grid">{services.map(({name,description,duration,icon:Icon})=><button type="button" key={name} className={`service-card ${form.service===name?'selected':''}`} onClick={()=>update('service',name)}><span className="service-icon"><Icon size={22}/></span><strong>{name}</strong><p>{description}</p><small>{duration}</small></button>)}</div></section>

    <section className="container content-section"><div className="booking-grid"><form className="panel booking-panel" onSubmit={submit}><div className="panel-heading"><div><span className="step">01</span><div><h2>Dados do agendamento</h2><p>Preencha seus dados para reservar.</p></div></div></div><div className="form-grid"><label>Nome completo *<input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Ex.: Ana Souza"/></label><label>Telefone *<input value={form.phone} onChange={e=>update('phone',formatPhone(e.target.value))} placeholder="(11) 99999-9999" inputMode="tel"/></label><label className="full">Serviço *<select value={form.service} onChange={e=>update('service',e.target.value)}><option value="">Selecione um serviço</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Data *<input type="date" min={minDate} value={form.date} onChange={e=>update('date',e.target.value)}/></label><label>Horário escolhido<input value={form.time||'Selecione ao lado'} readOnly disabled/></label><label className="full">Observações <textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Conte algo importante para o atendimento (opcional)." rows={3}/></label></div>{error&&<div className="alert error">{error}</div>}<button className="primary-button" type="submit">Confirmar agendamento <CalendarCheck size={18}/></button><p className="privacy-note"><ShieldCheck size={14}/> Seus dados são utilizados apenas para este agendamento.</p></form>

    <aside className="panel availability"><div className="panel-heading"><div><span className="step">02</span><div><h2>Escolha o horário</h2><p>{form.date?'Horários disponíveis na data':'Selecione primeiro uma data'}</p></div></div></div><div className="time-grid">{times.map(time=>{const busy=occupied.includes(time);return <button type="button" disabled={!form.date||busy} onClick={()=>update('time',time)} key={time} className={`time-chip ${busy?'busy':''} ${form.time===time?'selected':''}`}><span>{time}</span><small>{busy?'Ocupado':form.time===time?'Selecionado':'Disponível'}</small></button>})}</div><div className="availability-legend"><span><i className="dot free"/>Disponível</span><span><i className="dot busy"/>Ocupado</span></div></aside></div></section>

    {confirmation&&<div className="modal-backdrop"><div className="confirmation-modal"><button className="modal-close" onClick={()=>setConfirmation(null)}><X size={20}/></button><span className="success-icon"><CheckCircle2 size={38}/></span><span className="eyebrow">Tudo certo</span><h2>Agendamento confirmado!</h2><p>Olá, <strong>{confirmation.name}</strong>. Seu atendimento foi reservado com sucesso.</p><div className="confirmation-details"><div><span>Serviço</span><strong>{confirmation.service}</strong></div><div><span>Data</span><strong>{new Date(`${confirmation.date}T12:00:00`).toLocaleDateString('pt-BR')}</strong></div><div><span>Horário</span><strong>{confirmation.time}</strong></div></div><button className="primary-button" onClick={()=>setConfirmation(null)}>Concluir</button></div></div>}
  </>;
}
